[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.install]
cmds = ["bundle install"]

[phases.build]
cmds = [
  "bundle exec rails assets:precompile",
  "bundle exec rails db:prepare"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"

[variables]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
